### ISSUE TITLE
[phantom] Wait timeout of 5000ms expired, exiting.

### ISSUE THREAD

**Issue by Sc0th** [russss/barclayscrape#22] opened 2017-09-12 14:10 UTC
Hi,

Thank you @carpii for looking at this, I have been out of town and was keen to get it up and running again.

Sadly, my lack of knowledge has me stuck again, every time I run it I get -

> [error] [phantom] Wait timeout of 5000ms expired, exiting.
> Wait timeout of 5000ms expired, exiting.

I tried increasing the casperjs timeout, same result, just takes longer to fail...

I have even spun up clean VM (CentOS7) and started from scratch, same results.

If you are able to offer any pointers as to where I am going wrong, would be much appreciated.

**Comment by carpii** [comment] 2017-09-12 15:17
Hi @Sc0th 

Are you sure you copied your config.js over to the new VM?

Try changing get_combined_ofx.js, so casper outputs more debug info...

````
var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug',
    etc
````

This should give you an idea of which step is not progressing properly. 
I've confirmed it is still working ok for me

**Comment by Sc0th** [comment] 2017-09-13 00:59
Hey @carpii 

config.js is present and correct, output from debug is as follow, hope this give you a clue as to what I have got wrong! (please excuse the ASCII codes)

``[36m[info][0m [phantom] Starting...
[36m[info][0m [phantom] Running suite: 3 steps
[32;1m[debug][0m [phantom] opening url: https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do, HTTP GET
[32;1m[debug][0m [phantom] Navigation requested: url=https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do, type=Other, willNavigate=true, isMainFrame=true
[33m[warning][0m [phantom] Loading resource failed with status=fail: https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do
[32;1m[debug][0m [phantom] Successfully injected Casper client-side utilities
[32;1m[debug][0m [phantom] Login stage 1
[32;1m[debug][0m [phantom] Login stage 2 - Passcode and Memoerable word
[36m[info][0m [phantom] Step loginStageOne 2/3: done in 1044ms.
[36m[info][0m [phantom] Step _step 3/6: done in 1064ms.
[33m[warning][0m [phantom] Casper.waitFor() timeout
[37;41;1m[error][0m [phantom] Wait timeout of 5000ms expired, exiting.
[37;41;1mWait timeout of 5000ms expired, exiting.[0m

**Comment by Sc0th** [comment] 2017-09-13 01:32
looks to be something related to ssl, can't quite see how to set the '--ignore-ssl-errors=true' option, will keep poking about...

**Comment by Sc0th** [comment] 2017-09-14 09:07
running with:

casperjs --ignore-ssl-errors=tue --ssl-protocol=any --debug=yes ./get_combined_ofx.js 

provides:

[debug] [phantom] opening url: https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do, HTTP GET
[debug] [phantom] Navigation requested: url=https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do, type=Other, willNavigate=true, isMainFrame=true
2017-09-14T17:04:58 [DEBUG] Network - Resource request error: 6 ( "**SSL handshake failed**" ) URL: "https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do"
2017-09-14T17:04:58 [DEBUG] WebPage - updateLoadingProgress: 100
2017-09-14T17:04:58 [DEBUG] WebPage - evaluateJavaScript "(function() { return (function () {
        return typeof __utils__ === "object";
    })(); })()"
2017-09-14T17:04:58 [DEBUG] WebPage - evaluateJavaScript result QVariant(bool, false)
[warning] [phantom] Loading resource failed with status=fail: https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do

**Comment by carpii** [comment] 2017-09-14 10:52
What version of phantomjs and casperjs?

Im not seeing SSL issues, although I'm running on a Mac (with casperjs 1.1.4 and phantomjs 2.1.1)

````
--ignore-ssl-errors=tue 
````

This was just a typo?

**Comment by Sc0th** [comment] 2017-09-14 10:59
Hi, yes it was a typo, does not work when my phat fingers get it right either.

[root@nox barclayscrape]# phantomjs --version
1.9.6
[root@nox barclayscrape]# casperjs --version
1.1.4
[root@nox barclayscrape]#

I have tried with 2.1.1 also, made no odds.

What is frustration is that the arguments seem to be ignored, the head of the debug output states -

`2017-09-14T18:58:35 [DEBUG] Phantom - execute: Configuration
2017-09-14T18:58:35 [DEBUG]      0 objectName : ""
2017-09-14T18:58:35 [DEBUG]      1 cookiesFile : ""
2017-09-14T18:58:35 [DEBUG]      2 diskCacheEnabled : "false"
2017-09-14T18:58:35 [DEBUG]      3 maxDiskCacheSize : "-1"
2017-09-14T18:58:35 [DEBUG]      4 ignoreSslErrors : "false"
2017-09-14T18:58:35 [DEBUG]      5 localToRemoteUrlAccessEnabled : "false"
2017-09-14T18:58:35 [DEBUG]      6 outputEncoding : "UTF-8"
2017-09-14T18:58:35 [DEBUG]      7 proxyType : "http"
2017-09-14T18:58:35 [DEBUG]      8 proxy : ":1080"
2017-09-14T18:58:35 [DEBUG]      9 proxyAuth : ":"
2017-09-14T18:58:35 [DEBUG]      10 scriptEncoding : "UTF-8"
2017-09-14T18:58:35 [DEBUG]      11 webSecurityEnabled : "true"
2017-09-14T18:58:35 [DEBUG]      12 offlineStoragePath : ""
2017-09-14T18:58:35 [DEBUG]      13 offlineStorageDefaultQuota : "-1"
2017-09-14T18:58:35 [DEBUG]      14 printDebugMessages : "true"
2017-09-14T18:58:35 [DEBUG]      15 javascriptCanOpenWindows : "true"
2017-09-14T18:58:35 [DEBUG]      16 javascriptCanCloseWindows : "true"
2017-09-14T18:58:35 [DEBUG]      17 sslProtocol : "sslv3"
`

I suspect getting the two ssl related variables to switch would fix the problem I am seeing. If I could figure out how... :)

**Comment by carpii** [comment] 2017-09-14 11:06
Do you get a different error if you prevent it trying to choose sslv3?

````
--ssl-protocol=tlsv1
````

For whatever reason, when I run your command, the ignore-ssl option does seem to be getting passed through to phantomjs properly.
I'd stick with trying to get phantomjs 2.1.1 working, I seem to recall it contains other unrelated fixes which are needed. 

````
casperjs --ignore-ssl-errors=true --ssl-protocol=any --debug=yes ./get_combined_ofx.js
2017-09-14T12:02:31 [DEBUG] CookieJar - Created but will not store cookies (use option '--cookies-file=<filename>' to enable persistent cookie storage)
2017-09-14T12:02:32 [DEBUG] Set  "http"  proxy to:  "" : 1080
2017-09-14T12:02:32 [DEBUG] Phantom - execute: Configuration
2017-09-14T12:02:32 [DEBUG]      0 objectName : ""
2017-09-14T12:02:32 [DEBUG]      1 cookiesFile : ""
2017-09-14T12:02:32 [DEBUG]      2 diskCacheEnabled : "false"
2017-09-14T12:02:32 [DEBUG]      3 maxDiskCacheSize : "-1"
2017-09-14T12:02:32 [DEBUG]      4 diskCachePath : ""
2017-09-14T12:02:32 [DEBUG]      5 ignoreSslErrors : "true"
````

**Comment by Sc0th** [comment] 2017-09-14 11:23
Woooo Hoooo!

Blew it all away, pulled fresh from git, updated phantomjs to 2.1.1, and it bloomin' well works, 

Thank you so much for your help and guidance!

**Comment by carpii** [comment] 2017-09-14 11:27
No probs. Glad you got it working, because I was just about of ideas ;-D

**Comment by carpii** [comment] 2017-10-22 21:08
@russss Could we close this ticket please?

**Closed** 2017-10-22 22:26 UTC
